--- a/Makefile
+++ b/Makefile
@@ -73,7 +73,8 @@ assets:
 promu:
 	@echo ">> fetching promu"
 	@GOOS=$(shell uname -s | tr A-Z a-z) \
-	GOARCH=$(subst x86_64,amd64,$(patsubst i%86,386,$(shell uname -m))) \
+	GOARCH=$(arm) \
+	GOARM=7 \
 	$(GO) get -u github.com/prometheus/promu


